# Deployment Pipeline.
trigger: none
pr: none

variables:
# Variables group

# pipeline variables

stages:

- stage: Deployment
  jobs:    
  - deployment: Code_Deployment
    displayName: Deploy Code  
    pool:
      vmImage: 'vs2017-win2016'
    environment: 'environmentName' #environment name to add the checks and approvals

    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
			displayName: 'Download required artifact'
			inputs:
			  buildType: specific
			  project: ''
			  definition: ''
			  buildVersionToDownload: specific
			  pipelineId: ''
			  artifactName: 'BuildArtifact1'
			  itemPattern: '*.zip'
			  targetPath: '$(System.DefaultWorkingDirectory)'

		  - task: AzureWebApp@1
		    displayName: 'Deploy to offline slot'
		    inputs:
		      azureSubscription: ''
		      appType: ''
		      appName: ''
		      deployToSlotOrASE: 
		      resourceGroupName: ''
		      slotName: ''
		      package: '$(System.DefaultWorkingDirectory)\*.zip'
		      deploymentMethod: 'zipDeploy'
          
		  # Add some tasks to verify the delployment anf then swap using the below task to the main slot
          - task: AzureAppServiceManage@0
            displayName: 'Swap Offline with $(_prodSlot) Channel'
            condition:  #Add the required condition here
            inputs:
              azureSubscription: ''
              WebAppName: ''
              ResourceGroupName: ''
              action: ''
              swapWithProduction: ''
              SourceSlot: ''
              targetSlot: ''
